// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCS_Employee_Entity_CodeFirstApproach;

#nullable disable

namespace TCS_Employee_Entity_CodeFirstApproach.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20241205153948_Orders")]
    partial class Orders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TCS_Employee_Entity_CodeFirstApproach.Employee", b =>
                {
                    b.Property<int>("empid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empid"));

                    b.Property<string>("empname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("empsalary")
                        .HasColumnType("int");

                    b.HasKey("empid");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("TCS_Employee_Entity_CodeFirstApproach.Entites.Orders", b =>
                {
                    b.Property<int>("orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderid"));

                    b.Property<string>("orderlocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ordername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("orderid");

                    b.ToTable("orderss");
                });
#pragma warning restore 612, 618
        }
    }
}
